name: code_challenge_news_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  domain_layer:
    path: packages/domain_layer
  injection_layer:
    path: packages/injection_layer
  resourcing:
    path: packages/resourcing
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  infinite_scroll_pagination: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Fredoka-Light.ttf
          weight: 300  # Light
        - asset: assets/fonts/Fredoka-Regular.ttf
          weight: 400  # Regular
        - asset: assets/fonts/Fredoka-Medium.ttf
          weight: 500  # Medium
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          weight: 600  # SemiBold
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700  # Bold
  assets:
    - assets/
    - assets/fonts/


  uses-material-design: true