name: resourcing
description: A helper package for resourcing in Flutter.
publish_to: ‘none’ # Prevents accidental publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true