name: data_layer
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  retrofit: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.0.0
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.9
  test: ^1.25.15
