name: data_layer
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  domain_layer:
    path: ../domain_layer
  hive: ^2.2.3
  connectivity_plus: ^6.1.4

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^5.0.0
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  test: ^1.25.15
  hive_test: ^1.0.1
