name: injection_layer
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  get_it: ^8.0.3
  domain_layer:
    path: ../domain_layer
  data_layer:
    path: ../data_layer
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
